[package]
name = "protos-rust"
version = "0.0.0-955e769"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Protocol Buffer definitions for Harvest Hub"
repository = "https://github.com/harvesthub-gardening-tool/protos-rust"

[dependencies]
prost = "0.14"
tonic = "0.14"
tonic-prost = "0.14"
