// @generated
// This file is @generated by prost-build.
/// ====== Messages ======
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterResponse {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginRequest {
    #[prost(string, tag="1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LoginResponse {
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
// ---- Hub provisioning ----

#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssociateHubRequest {
    /// Unique device identifier (UUID) generated by the hub at first flash and printed in the QR code.
    #[prost(string, tag="1")]
    pub device_id: ::prost::alloc::string::String,
    /// Per-device secret (hex-encoded) printed in the QR code. Used to authenticate the hub during ClaimHubToken.
    #[prost(string, tag="2")]
    pub hub_secret: ::prost::alloc::string::String,
    /// Human-readable name chosen by the user (e.g. "Greenhouse Hub").
    #[prost(string, tag="3")]
    pub hub_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssociateHubResponse {
    /// Server-side hub ID (database primary key, stringified).
    #[prost(string, tag="1")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub hub_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClaimHubTokenRequest {
    #[prost(string, tag="1")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub hub_secret: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClaimHubTokenResponse {
    /// Hub service-account JWT. Returned exactly once; the hub must persist it.
    #[prost(string, tag="1")]
    pub token: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListHubsRequest {
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HubInfo {
    /// Server-side hub ID (database primary key, stringified).
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub device_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub hub_name: ::prost::alloc::string::String,
    /// Unix milliseconds
    #[prost(int64, tag="4")]
    pub created_at: i64,
    /// true once the hub has retrieved its JWT
    #[prost(bool, tag="5")]
    pub claimed: bool,
    #[prost(bool, tag="6")]
    pub revoked: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListHubsResponse {
    #[prost(message, repeated, tag="1")]
    pub hubs: ::prost::alloc::vec::Vec<HubInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeHubRequest {
    /// Server-side hub ID returned by AssociateHub / ListHubs.
    #[prost(string, tag="1")]
    pub hub_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeHubResponse {
}
include!("auth.v2.tonic.rs");
// @@protoc_insertion_point(module)