// @generated
// This file is @generated by prost-build.
/// ====== Messages ======
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InsertSensorDataRequest {
    /// Probe identifier (BLE MAC or stable hardware ID)
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Celsius
    #[prost(double, tag="2")]
    pub temperature: f64,
    /// Percent (0-100)
    #[prost(double, tag="3")]
    pub humidity: f64,
    /// Percent (0-100)
    #[prost(double, tag="4")]
    pub soil_moisture: f64,
    /// Unix milliseconds
    #[prost(int64, tag="5")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InsertSensorDataResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSummaryRequest {
    /// If empty, summarises across all nodes the caller owns.
    #[prost(string, optional, tag="1")]
    pub node_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Sliding window in hours (default 24).
    #[prost(int32, optional, tag="2")]
    pub hours: ::core::option::Option<i32>,
    /// Restrict the summary to a single hub owned by the caller. If unset, all hubs owned by the caller are included.
    #[prost(string, optional, tag="3")]
    pub hub_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSummaryResponse {
    #[prost(message, repeated, tag="1")]
    pub summaries: ::prost::alloc::vec::Vec<SensorSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SensorSummary {
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Unix milliseconds
    #[prost(int64, tag="2")]
    pub interval_start: i64,
    #[prost(double, tag="3")]
    pub avg_temperature: f64,
    #[prost(double, tag="4")]
    pub avg_humidity: f64,
    #[prost(double, tag="5")]
    pub avg_soil_moisture: f64,
    /// Celsius
    #[prost(double, tag="6")]
    pub max_temperature: f64,
    /// ID of the hub that owns the probe (matches `hubs.id`).
    #[prost(string, tag="7")]
    pub hub_id: ::prost::alloc::string::String,
}
include!("garden.v2.tonic.rs");
// @@protoc_insertion_point(module)