// @generated
// This file is @generated by prost-build.
/// ====== Messages ======
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InsertSensorDataRequest {
    /// Probe identifier (BLE MAC or stable hardware ID)
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Celsius
    #[prost(double, tag="2")]
    pub air_temperature: f64,
    /// Percent (0-100)
    #[prost(double, tag="3")]
    pub air_humidity: f64,
    /// Percent (0-100)
    #[prost(double, tag="4")]
    pub soil_humidity: f64,
    /// Unix milliseconds
    #[prost(int64, tag="5")]
    pub timestamp: i64,
    /// Pascals
    #[prost(double, tag="6")]
    pub air_pressure: f64,
    /// Celsius
    #[prost(double, tag="7")]
    pub soil_temperature: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InsertSensorDataResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSummaryRequest {
    /// If empty, summarises across all nodes the caller owns.
    #[prost(string, optional, tag="1")]
    pub node_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Sliding window in hours (default 24).
    #[prost(int32, optional, tag="2")]
    pub hours: ::core::option::Option<i32>,
    /// Restrict the summary to a single hub owned by the caller. If unset, all hubs owned by the caller are included.
    #[prost(string, optional, tag="3")]
    pub hub_id: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSummaryResponse {
    #[prost(message, repeated, tag="1")]
    pub summaries: ::prost::alloc::vec::Vec<SensorSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SensorSummary {
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Unix milliseconds
    #[prost(int64, tag="2")]
    pub interval_start: i64,
    /// Celsius
    #[prost(double, tag="3")]
    pub avg_air_temperature: f64,
    /// Percent (0-100)
    #[prost(double, tag="4")]
    pub avg_air_humidity: f64,
    /// Percent (0-100)
    #[prost(double, tag="5")]
    pub avg_soil_humidity: f64,
    /// Celsius
    #[prost(double, tag="6")]
    pub max_air_temperature: f64,
    /// ID of the hub that owns the probe (matches `hubs.id`).
    #[prost(string, tag="7")]
    pub hub_id: ::prost::alloc::string::String,
    /// Pascals
    #[prost(double, tag="8")]
    pub avg_air_pressure: f64,
    /// Celsius
    #[prost(double, tag="9")]
    pub avg_soil_temperature: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListProbesForHubNameRequest {
    /// Human-readable hub name (matched against the hub_name set during AssociateHub).
    #[prost(string, tag="1")]
    pub hub_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProbeInfo {
    /// Probe identifier (BLE MAC or stable hardware ID).
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListProbesForHubNameResponse {
    #[prost(message, repeated, tag="1")]
    pub probes: ::prost::alloc::vec::Vec<ProbeInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SensorReading {
    /// Probe identifier (BLE MAC or stable hardware ID).
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Unix milliseconds of the reading timestamp.
    #[prost(int64, tag="2")]
    pub time: i64,
    /// Celsius
    #[prost(double, tag="3")]
    pub air_temperature: f64,
    /// Pascals
    #[prost(double, tag="4")]
    pub air_pressure: f64,
    /// Percent (0-100)
    #[prost(double, tag="5")]
    pub air_humidity: f64,
    /// Celsius
    #[prost(double, tag="6")]
    pub soil_temperature: f64,
    /// Percent (0-100)
    #[prost(double, tag="7")]
    pub soil_humidity: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetLastRequest {
    /// Probe identifier (BLE MAC or stable hardware ID).
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetLastResponse {
    #[prost(message, optional, tag="1")]
    pub reading: ::core::option::Option<SensorReading>,
}
include!("garden.v2.tonic.rs");
// @@protoc_insertion_point(module)