// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendMessageRequest {
    #[prost(string, tag="1")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub plants: ::prost::alloc::vec::Vec<ChatPlantContext>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SendMessageResponse {
    #[prost(string, tag="1")]
    pub reply: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ChatPlantContext {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub quantity: i32,
    #[prost(string, tag="4")]
    pub probe_node_id: ::prost::alloc::string::String,
}
include!("chat.v1.tonic.rs");
// @@protoc_insertion_point(module)