// @generated
// This file is @generated by prost-build.
/// ====== Messages ======
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MotorCommand {
    #[prost(string, tag="1")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(enumeration="MotorCommandAction", tag="5")]
    pub action: i32,
    #[prost(int32, tag="6")]
    pub duration_ms: i32,
    #[prost(string, tag="7")]
    pub requested_by_user_id: ::prost::alloc::string::String,
    /// Unix milliseconds
    #[prost(int64, tag="8")]
    pub created_at: i64,
    /// Unix milliseconds
    #[prost(int64, tag="9")]
    pub expires_at: i64,
    /// Unix milliseconds, 0 when not leased
    #[prost(int64, tag="10")]
    pub lease_expires_at: i64,
    #[prost(enumeration="MotorCommandStatus", tag="11")]
    pub status: i32,
    #[prost(enumeration="MotorCommandReasonCode", tag="12")]
    pub reason_code: i32,
    #[prost(string, tag="13")]
    pub reason_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateMotorCommandRequest {
    #[prost(string, tag="1")]
    pub idempotency_key: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(enumeration="MotorCommandAction", tag="4")]
    pub action: i32,
    #[prost(int32, tag="5")]
    pub duration_ms: i32,
    /// Unix milliseconds
    #[prost(int64, tag="6")]
    pub expires_at: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateMotorCommandResponse {
    #[prost(message, optional, tag="1")]
    pub command: ::core::option::Option<MotorCommand>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMotorCommandStatusRequest {
    #[prost(string, tag="1")]
    pub command_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetMotorCommandStatusResponse {
    #[prost(message, optional, tag="1")]
    pub command: ::core::option::Option<MotorCommand>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PullPendingMotorCommandsRequest {
    #[prost(string, tag="1")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub max_commands: i32,
    #[prost(int32, tag="3")]
    pub lease_duration_ms: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PullPendingMotorCommandsResponse {
    #[prost(message, repeated, tag="1")]
    pub commands: ::prost::alloc::vec::Vec<MotorCommand>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckMotorCommandEventRequest {
    #[prost(string, tag="1")]
    pub command_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub hub_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub node_id: ::prost::alloc::string::String,
    #[prost(enumeration="MotorCommandStatus", tag="4")]
    pub status: i32,
    #[prost(enumeration="MotorCommandReasonCode", tag="5")]
    pub reason_code: i32,
    #[prost(string, tag="6")]
    pub reason_message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AckMotorCommandEventResponse {
    #[prost(message, optional, tag="1")]
    pub command: ::core::option::Option<MotorCommand>,
}
/// ====== Enums ======
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MotorCommandAction {
    Unspecified = 0,
    RunForDuration = 1,
    Stop = 2,
}
impl MotorCommandAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MOTOR_COMMAND_ACTION_UNSPECIFIED",
            Self::RunForDuration => "MOTOR_COMMAND_ACTION_RUN_FOR_DURATION",
            Self::Stop => "MOTOR_COMMAND_ACTION_STOP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOTOR_COMMAND_ACTION_UNSPECIFIED" => Some(Self::Unspecified),
            "MOTOR_COMMAND_ACTION_RUN_FOR_DURATION" => Some(Self::RunForDuration),
            "MOTOR_COMMAND_ACTION_STOP" => Some(Self::Stop),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MotorCommandStatus {
    /// Invalid/default value.
    Unspecified = 0,
    Queued = 1,
    LeasedToHub = 2,
    SentToProbe = 3,
    Executing = 4,
    Succeeded = 5,
    Failed = 6,
    Expired = 7,
    Cancelled = 8,
}
impl MotorCommandStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MOTOR_COMMAND_STATUS_UNSPECIFIED",
            Self::Queued => "MOTOR_COMMAND_STATUS_QUEUED",
            Self::LeasedToHub => "MOTOR_COMMAND_STATUS_LEASED_TO_HUB",
            Self::SentToProbe => "MOTOR_COMMAND_STATUS_SENT_TO_PROBE",
            Self::Executing => "MOTOR_COMMAND_STATUS_EXECUTING",
            Self::Succeeded => "MOTOR_COMMAND_STATUS_SUCCEEDED",
            Self::Failed => "MOTOR_COMMAND_STATUS_FAILED",
            Self::Expired => "MOTOR_COMMAND_STATUS_EXPIRED",
            Self::Cancelled => "MOTOR_COMMAND_STATUS_CANCELLED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOTOR_COMMAND_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "MOTOR_COMMAND_STATUS_QUEUED" => Some(Self::Queued),
            "MOTOR_COMMAND_STATUS_LEASED_TO_HUB" => Some(Self::LeasedToHub),
            "MOTOR_COMMAND_STATUS_SENT_TO_PROBE" => Some(Self::SentToProbe),
            "MOTOR_COMMAND_STATUS_EXECUTING" => Some(Self::Executing),
            "MOTOR_COMMAND_STATUS_SUCCEEDED" => Some(Self::Succeeded),
            "MOTOR_COMMAND_STATUS_FAILED" => Some(Self::Failed),
            "MOTOR_COMMAND_STATUS_EXPIRED" => Some(Self::Expired),
            "MOTOR_COMMAND_STATUS_CANCELLED" => Some(Self::Cancelled),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MotorCommandReasonCode {
    /// NONE.
    Unspecified = 0,
    None = 1,
    Unauthorized = 2,
    Expired = 3,
    Duplicate = 4,
    ProbeUnreachable = 5,
    BleWriteFailed = 6,
    UartTimeout = 7,
    UartRejected = 8,
    SafetyLimitExceeded = 9,
}
impl MotorCommandReasonCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "MOTOR_COMMAND_REASON_CODE_UNSPECIFIED",
            Self::None => "MOTOR_COMMAND_REASON_CODE_NONE",
            Self::Unauthorized => "MOTOR_COMMAND_REASON_CODE_UNAUTHORIZED",
            Self::Expired => "MOTOR_COMMAND_REASON_CODE_EXPIRED",
            Self::Duplicate => "MOTOR_COMMAND_REASON_CODE_DUPLICATE",
            Self::ProbeUnreachable => "MOTOR_COMMAND_REASON_CODE_PROBE_UNREACHABLE",
            Self::BleWriteFailed => "MOTOR_COMMAND_REASON_CODE_BLE_WRITE_FAILED",
            Self::UartTimeout => "MOTOR_COMMAND_REASON_CODE_UART_TIMEOUT",
            Self::UartRejected => "MOTOR_COMMAND_REASON_CODE_UART_REJECTED",
            Self::SafetyLimitExceeded => "MOTOR_COMMAND_REASON_CODE_SAFETY_LIMIT_EXCEEDED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MOTOR_COMMAND_REASON_CODE_UNSPECIFIED" => Some(Self::Unspecified),
            "MOTOR_COMMAND_REASON_CODE_NONE" => Some(Self::None),
            "MOTOR_COMMAND_REASON_CODE_UNAUTHORIZED" => Some(Self::Unauthorized),
            "MOTOR_COMMAND_REASON_CODE_EXPIRED" => Some(Self::Expired),
            "MOTOR_COMMAND_REASON_CODE_DUPLICATE" => Some(Self::Duplicate),
            "MOTOR_COMMAND_REASON_CODE_PROBE_UNREACHABLE" => Some(Self::ProbeUnreachable),
            "MOTOR_COMMAND_REASON_CODE_BLE_WRITE_FAILED" => Some(Self::BleWriteFailed),
            "MOTOR_COMMAND_REASON_CODE_UART_TIMEOUT" => Some(Self::UartTimeout),
            "MOTOR_COMMAND_REASON_CODE_UART_REJECTED" => Some(Self::UartRejected),
            "MOTOR_COMMAND_REASON_CODE_SAFETY_LIMIT_EXCEEDED" => Some(Self::SafetyLimitExceeded),
            _ => None,
        }
    }
}
include!("control.v1.tonic.rs");
// @@protoc_insertion_point(module)