// @generated
// This file is @generated by prost-build.
// ====== Messages ======

/// * Requête d'insertion d'une mesure 
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InsertSensorDataRequest {
    /// ID du noeud/capteur (utilisé aussi dans le path)
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// °C
    #[prost(double, tag="2")]
    pub temperature: f64,
    /// %
    #[prost(double, tag="3")]
    pub humidity: f64,
    /// %
    #[prost(double, tag="4")]
    pub soil_moisture: f64,
    /// Unix ms
    #[prost(int64, tag="5")]
    pub timestamp: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InsertSensorDataResponse {
    #[prost(bool, tag="1")]
    pub success: bool,
    #[prost(string, tag="2")]
    pub message: ::prost::alloc::string::String,
}
/// * Requête de résumé (query params si route GET sans {node_id}) 
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSummaryRequest {
    /// Si vide, résume tous les noeuds
    #[prost(string, optional, tag="1")]
    pub node_id: ::core::option::Option<::prost::alloc::string::String>,
    /// Fenêtre glissante en heures (defaut 24)
    #[prost(int32, optional, tag="2")]
    pub hours: ::core::option::Option<i32>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetSummaryResponse {
    #[prost(message, repeated, tag="1")]
    pub summaries: ::prost::alloc::vec::Vec<SensorSummary>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SensorSummary {
    #[prost(string, tag="1")]
    pub node_id: ::prost::alloc::string::String,
    /// Unix ms
    #[prost(int64, tag="2")]
    pub interval_start: i64,
    #[prost(double, tag="3")]
    pub avg_temperature: f64,
    #[prost(double, tag="4")]
    pub avg_humidity: f64,
    #[prost(double, tag="5")]
    pub avg_soil_moisture: f64,
    /// champ ajouté pour test
    ///
    /// °C (optionnel par défaut en proto3)
    #[prost(double, tag="6")]
    pub max_temperature: f64,
}
include!("garden.v1.tonic.rs");
// @@protoc_insertion_point(module)